#
# This is a special schema.rb file which loads all of the files from
# the db/migrate directory in order.  It is installed by running the task
# "rake db:auto:enable" (supplied by the auto_migrations_by_default plugin).
#
# It is used in conjunction with the auto_migrations plugin to
# automatically apply deltas to the target schema, while still allowing
# migrations generated by script/generate to work correctly.
#
# This enables easy switching back and forth between auto and regular
# migrations.  To switch to regular migrations, use "rake db:auto:disable"
#
ActiveRecord::Schema.define do
  migrate = AutoMigrationsByDefault::Migrate.new
  migrate.run
end